name: deploy

on:
  schedule:
    - cron: '*/5 * * * *'

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_PAT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash deploy.sh
